# Generated by Django 5.0.7 on 2024-07-27 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_song_genre_song_language_song_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='owner',
        ),
    ]
